[phases.setup]
nixPkgs = ['openjdk21']

[phases.install]
cmds = ['chmod +x ./gradlew']

[phases.build]
cmds = ['./gradlew clean bootJar -x test --no-daemon --info']

[start]
cmd = 'java -Dserver.port=$PORT -Dspring.profiles.active=prod -jar $(ls build/libs/*-SNAPSHOT.jar | grep -v plain)'
